# Generated by Django 3.2.7 on 2021-11-09 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo_hosting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='photo_hosting.collections'),
        ),
    ]
