# Generated by Django 3.2.7 on 2021-11-26 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo_hosting', '0006_auto_20211126_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='photo_hosting.userprofile'),
        ),
    ]
