version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3307:3306'
    environment:
       MYSQL_DATABASE: 'photo_hosting'
       MYSQL_USER: 'user'
       MYSQL_PASSWORD: '1234'
       MYSQL_ROOT_PASSWORD: '1234'
    volumes:
      - .setup.sql:/docker-entrypoint-initbd.d/setup.sql

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db