# Generated by Django 3.2.7 on 2021-12-14 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo_hosting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavCollections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo_hosting.collections', verbose_name='Collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo_hosting.userprofile', verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Favourites',
                'verbose_name_plural': 'Favourites',
            },
        ),
    ]
