# Generated by Django 3.2.7 on 2021-11-15 17:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photo_hosting', '0003_auto_20211112_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collections',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='photo_hosting.userprofile'),
            preserve_default=False,
        ),
    ]
